learning_users/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

#template URLs

app_name='basic_app'

urlpatterns=[
   path('register/',views.register,name='register'),
   path('user_login/',views.user_login,name='user_login'),
   path('bluechip.html',views.bluechip,name='bluechip'),
  

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views


urlpatterns = [
    #path('',views.index,name='index'),
    path('',views.index1,name='index1'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portofolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portofolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def bluechip(request):
    return render(request,'basic_app/bluechip.html',{})

def index1(request):
    return render(request,'basic_app/index1.html')


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index1'))

def register(request):

    registered=False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'basic_app/registration.html',
                                  {'user_form':user_form,
                                  'profile_form':profile_form,
                                  'registered':registered})



def user_login(request):

    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,'basic_app/index1.html')
            else:
                return HttpResponse('Account not Active')
        else:
            print("Someone tried to login but failed !")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Invalid login details passed !")
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blue Chip</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">


  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a href="{% url 'index1' %}">BLUE CHIP</a></li>
          <li class="navbar-link"><a href="{% url 'admin:index'%}">Admin</a></li>


          {% if request.user.is_authenticated %}
             <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
             <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
           {% endif %}
        </ul>
      </div>
    </nav>


    <div class="container">
      {% block body-block %}
      {% endblock %}
    </div>
    <footer>
            <div class="container">
                <p>Copyright © Aditya Prakash. All Rights Reserved | Contact: 7979990752</p>
            </div>
        </footer>
  </body>
</html>

learning_users/templates/basic_app/bluechip.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blue Chip Game</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/bluechip.css' %}">


    </script>

    </script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a href="{% url 'index1' %}">BLUE CHIP</a></li>
          {% if request.user.is_authenticated %}
             <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
             <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
           {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container" align='center'>
      <h1>Welcome to Blue Chip Game !</h1>
      <h2>Connect four discs of same color to win.</h2>
      <table class="board">
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
        <tr>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
          <td><button type="button" name="button"></button></td>
        </tr>
      </table>
      <br>
      <br>

        <a href="{% url 'basic_app:bluechip' %}" class="btn btn-primary btn-lg"> Replay</a>
        <br>
        <br>
    </div>


    <footer>
            <div class="container">
                <p>Copyright © Aditya Prakash. All Rights Reserved | Contact: +91 79799 90752</p>
            </div>
        </footer>
        <script src="{% static "js/bluechip.js" %}">
        </script>
  </body>
</html>

learning_users/templates/basic_app/index1.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body-block %}
{% load static %}
<div class="jumbotron">

  {% if request.user.is_authenticated %}
  <h1>Hello, {{ request.user.username }}! Welcome to Blue Chip Game !</h1>
  <a href="{% url 'basic_app:bluechip' %}" class="btn btn-primary btn-lg"> Play game</a>
{% else %}
<h1>Welcome Guest!</h1>
<h2> Please sign in to play Blue chip game.</h2>
<a href="{% url 'basic_app:register' %}" class="btn btn-primary btn-lg"> Create an account</a>
<a href="{% url 'basic_app:user_login' %}" class="btn btn-primary btn-lg"> Sign In</a>
 {% endif %}
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body-block %}

<div class="jumbotron">
  <h1>Please login !</h1>
  <form  action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" class="btn btn-primary" value="Login">

  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load staticfiles %}


{% block body-block %}
<div class="jumbotron">
  {% if registered %}
     <h1>Thanks for registration !</h1>
     <h3>Please <a href="{% url 'basic_app:user_login' %}">Login</a> to continue.</h3>
  {% else %}
     <h2>Register Here!</h2>
     <h3>Fill out the form.</h3>

      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input class="btn btn-primary" type="submit" name="" value="Register">
      </form>
     {% endif %}
</div>
{% endblock %}